<?php
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/functions.php';
requireRole('administrator');

$pageTitle   = 'Backup / Restore';
$currentPage = 'backup';

$backupDir      = getSetting('backup_dir',      '/var/backups/steward');
$backupSchedule = getSetting('backup_schedule', 'off');
$backupRetain   = getSetting('backup_retain',   '14');
$backupHour     = getSetting('backup_hour',     '2');
$backupDow      = getSetting('backup_dow',      '0');
$backupDom      = getSetting('backup_dom',      '1');
$backupLastRun  = getSetting('backup_last_run');

$dirExists   = is_dir($backupDir);
$dirWritable = $dirExists && is_writable($backupDir);

include __DIR__ . '/../includes/header.php';
?>
<div class="page-content">

  <div class="page-header d-flex align-items-center gap-3 mb-4">
    <div>
      <h1 class="mb-0"><i class="bi bi-database"></i> Backup / Restore</h1>
      <p class="text-muted mb-0 mt-1">Download a full database backup or restore from a previous backup file.</p>
    </div>
  </div>

  <?= renderFlash() ?>

  <div class="row g-4">

    <!-- Backup -->
    <div class="col-lg-6">
      <div class="card h-100">
        <div class="card-header"><strong><i class="bi bi-download"></i> Download Backup</strong></div>
        <div class="card-body d-flex flex-column gap-3">
          <p class="mb-0 text-muted">
            Exports the complete database — all accounts, transactions, categories, settings, and users —
            as a <code>.sql</code> file you can store locally or use to restore later.
          </p>
          <ul class="mb-0 small text-muted ps-3">
            <li>Contains full schema and all data</li>
            <li>Compatible with any MySQL client</li>
            <li>Safe to restore on a fresh installation</li>
          </ul>
          <p class="mb-0 small text-muted">
            <strong>Download Configuration</strong> saves your <code>config/database.php</code> file, which holds
            the database host, name, and credentials. These two downloads together with the app files are
            everything you need for a full disaster recovery — no setup wizard required.
          </p>
          <div class="mt-auto pt-2 d-flex gap-2 flex-wrap">
            <a href="<?= BASE_PATH ?>/settings/backup_download" class="btn btn-primary">
              <i class="bi bi-download"></i> Download Backup
            </a>
            <a href="<?= BASE_PATH ?>/settings/download_config" class="btn btn-outline-secondary">
              <i class="bi bi-file-earmark-code"></i> Download Configuration
            </a>
          </div>
        </div>
      </div>
    </div>

    <!-- Restore -->
    <div class="col-lg-6">
      <div class="card h-100">
        <div class="card-header"><strong><i class="bi bi-upload"></i> Restore from Backup</strong></div>
        <div class="card-body d-flex flex-column gap-3">
          <div class="alert alert-warning mb-0 py-2">
            <i class="bi bi-exclamation-triangle-fill"></i>
            <strong>Destructive operation.</strong> Restoring will drop and recreate all tables,
            permanently replacing all current data. This cannot be undone.
          </div>
          <p class="mb-0 text-muted small">Upload a <code>.sql</code> backup file generated by this application.</p>
          <form method="post" action="<?= BASE_PATH ?>/settings/backup_restore"
                enctype="multipart/form-data" id="restoreForm">
            <?= csrfField() ?>
            <div class="mb-3">
              <label class="form-label fw-semibold">Backup File</label>
              <input type="file" name="backup_file" class="form-control" accept=".sql" required>
              <div class="form-text">Only <code>.sql</code> files generated by this app are supported.</div>
            </div>
            <button type="button" class="btn btn-danger" onclick="confirmRestore()">
              <i class="bi bi-arrow-counterclockwise"></i> Restore Database
            </button>
          </form>
        </div>
      </div>
    </div>

    <!-- Automatic Backups -->
    <div class="col-12">
      <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
          <strong><i class="bi bi-clock-history"></i> Automatic Backups</strong>
          <?php if ($backupLastRun): ?>
          <span class="text-muted small">Last run: <?= h($backupLastRun) ?></span>
          <?php endif; ?>
        </div>
        <div class="card-body">

          <?php if (!$dirExists || !$dirWritable): ?>
          <div class="alert alert-warning mb-3 py-2">
            <i class="bi bi-exclamation-triangle-fill"></i>
            <strong>Backup directory <?= $dirExists ? 'is not writable' : 'does not exist' ?>:</strong>
            <code><?= h($backupDir) ?></code><br>
            Run this once in your terminal to create it:
            <pre class="mb-0 mt-2 p-2 bg-dark text-light rounded small">sudo mkdir -p <?= h($backupDir) ?> &amp;&amp; sudo chown www-data:www-data <?= h($backupDir) ?></pre>
          </div>
          <?php endif; ?>

          <form id="scheduleForm">
            <?= csrfField() ?>
            <div class="row g-3">

              <div class="col-md-6">
                <label class="form-label fw-semibold">Backup Directory</label>
                <input type="text" class="form-control" id="backup_dir" name="backup_dir"
                       value="<?= h($backupDir) ?>" placeholder="/var/backups/steward">
                <div class="form-text">Must be outside the web root and writable by <code>www-data</code>.</div>
              </div>

              <div class="col-md-3">
                <label class="form-label fw-semibold">Keep</label>
                <div class="input-group">
                  <input type="number" class="form-control" id="backup_retain" name="backup_retain"
                         value="<?= h($backupRetain) ?>" min="1" max="365">
                  <span class="input-group-text">backups</span>
                </div>
                <div class="form-text">Oldest files are deleted automatically.</div>
              </div>

              <div class="col-md-3">
                <label class="form-label fw-semibold">Frequency</label>
                <select class="form-select" id="backup_schedule" name="backup_schedule">
                  <option value="off"     <?= $backupSchedule === 'off'     ? 'selected' : '' ?>>Disabled</option>
                  <option value="daily"   <?= $backupSchedule === 'daily'   ? 'selected' : '' ?>>Daily</option>
                  <option value="weekly"  <?= $backupSchedule === 'weekly'  ? 'selected' : '' ?>>Weekly</option>
                  <option value="monthly" <?= $backupSchedule === 'monthly' ? 'selected' : '' ?>>Monthly</option>
                </select>
              </div>

              <div class="col-md-3 schedule-time-row d-none">
                <label class="form-label fw-semibold">Time</label>
                <select class="form-select" id="backup_hour" name="backup_hour">
                  <?php
                  $labels = ['12:00 AM','1:00 AM','2:00 AM','3:00 AM','4:00 AM','5:00 AM',
                             '6:00 AM','7:00 AM','8:00 AM','9:00 AM','10:00 AM','11:00 AM',
                             '12:00 PM','1:00 PM','2:00 PM','3:00 PM','4:00 PM','5:00 PM',
                             '6:00 PM','7:00 PM','8:00 PM','9:00 PM','10:00 PM','11:00 PM'];
                  foreach ($labels as $i => $lbl):
                  ?>
                  <option value="<?= $i ?>" <?= (int)$backupHour === $i ? 'selected' : '' ?>><?= $lbl ?></option>
                  <?php endforeach; ?>
                </select>
              </div>

              <div class="col-md-3 schedule-dow-row d-none">
                <label class="form-label fw-semibold">Day of Week</label>
                <select class="form-select" id="backup_dow" name="backup_dow">
                  <?php
                  $days = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
                  foreach ($days as $i => $d):
                  ?>
                  <option value="<?= $i ?>" <?= (int)$backupDow === $i ? 'selected' : '' ?>><?= $d ?></option>
                  <?php endforeach; ?>
                </select>
              </div>

              <div class="col-md-3 schedule-dom-row d-none">
                <label class="form-label fw-semibold">Day of Month</label>
                <select class="form-select" id="backup_dom" name="backup_dom">
                  <?php for ($i = 1; $i <= 28; $i++): ?>
                  <option value="<?= $i ?>" <?= (int)$backupDom === $i ? 'selected' : '' ?>><?= $i ?></option>
                  <?php endfor; ?>
                </select>
              </div>

            </div>

            <div id="scheduleStatus" class="mt-3 d-none"></div>

            <div class="mt-3">
              <button type="button" class="btn btn-primary" onclick="saveSchedule()">
                <i class="bi bi-check-lg"></i> Save Schedule
              </button>
            </div>
          </form>

        </div>
      </div>
    </div>

    <!-- Stored Backups -->
    <div class="col-12">
      <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
          <strong><i class="bi bi-hdd-stack"></i> Stored Backups</strong>
          <button class="btn btn-sm btn-primary" onclick="runBackupNow()" id="runNowBtn">
            <i class="bi bi-play-fill"></i> Back Up Now
          </button>
        </div>
        <div class="card-body p-0">
          <div id="storedBackupsList">
            <div class="text-center text-muted py-4"><div class="spinner-border spinner-border-sm me-2"></div>Loading…</div>
          </div>
        </div>
      </div>
    </div>

    <!-- Reset -->
    <div class="col-12">
      <div class="card border-danger">
        <div class="card-header bg-danger text-white">
          <strong><i class="bi bi-exclamation-octagon-fill"></i> Reset Database</strong>
        </div>
        <div class="card-body d-flex flex-column gap-3">
          <div class="alert alert-danger mb-0 py-2">
            <i class="bi bi-exclamation-triangle-fill"></i>
            <strong>Irreversible.</strong> This permanently deletes all financial data and cannot be undone.
            Download a backup first!
          </div>
          <div class="row g-3">
            <div class="col-md-6">
              <p class="fw-semibold mb-1 small text-danger">Will be permanently deleted:</p>
              <ul class="mb-0 small text-muted ps-3">
                <li>All accounts and transactions</li>
                <li>All categories and payees</li>
                <li>All budgets and savings goals</li>
                <li>All scheduled bills and paycheck templates</li>
                <li>All non-index investments and their price history</li>
                <li>All favorite reports</li>
              </ul>
            </div>
            <div class="col-md-6">
              <p class="fw-semibold mb-1 small text-success">Will be preserved:</p>
              <ul class="mb-0 small text-muted ps-3">
                <li>All user accounts and passwords</li>
                <li>Application settings (price provider, etc.)</li>
                <li>Market index definitions and their price history</li>
              </ul>
            </div>
          </div>
          <div class="mt-auto pt-1">
            <button type="button" class="btn btn-danger" onclick="openResetModal()">
              <i class="bi bi-trash3-fill"></i> Reset All Data…
            </button>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

<!-- Reset confirmation modal -->
<div class="modal fade" id="resetModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content border-danger">
      <div class="modal-header bg-danger text-white">
        <h5 class="modal-title">
          <i class="bi bi-exclamation-octagon-fill me-1"></i> Confirm Database Reset
        </h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body">
        <p class="fw-semibold mb-2">You are about to permanently delete:</p>
        <ul class="small mb-3">
          <li>Every account, transaction, and split</li>
          <li>Every category, payee, budget, and savings goal</li>
          <li>Every scheduled bill and paycheck template</li>
          <li>All non-index investments and price history</li>
        </ul>
        <p class="mb-3 small">
          <span class="text-success fw-semibold">Preserved:</span>
          user accounts, application settings, and market index data.
        </p>
        <div class="alert alert-danger py-2 mb-3">
          <i class="bi bi-exclamation-triangle-fill"></i>
          <strong>This cannot be undone.</strong> If you have not downloaded a backup, close this dialog and do so now.
        </div>
        <label class="form-label fw-semibold">Type <code>I understand</code> to confirm:</label>
        <input type="text" id="resetConfirmInput" class="form-control" placeholder="I understand"
               autocomplete="off" spellcheck="false">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
        <form method="post" action="<?= BASE_PATH ?>/settings/reset" id="resetForm">
          <?= csrfField() ?>
          <input type="hidden" name="confirm" id="resetConfirmHidden" value="">
          <button type="submit" class="btn btn-danger" id="resetSubmitBtn" disabled>
            <i class="bi bi-trash3-fill"></i> Reset All Data
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Restore progress overlay -->
<div class="modal fade" id="restoreProgressModal" tabindex="-1" aria-hidden="true"
     data-bs-backdrop="static" data-bs-keyboard="false">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body text-center py-4">
        <div class="spinner-border text-primary mb-3" role="status"></div>
        <h5 class="mb-2">Restoring Backup…</h5>
        <p class="text-muted mb-0">This can take a while for large backups. Please don't close or refresh this tab.</p>
      </div>
    </div>
  </div>
</div>

<script>
const BASE_PATH = '<?= BASE_PATH ?>';
function getCsrfToken() {
  const el = document.querySelector('#scheduleForm input[name="csrf_token"]');
  return el ? el.value : '';
}

// ---- Schedule UI --------------------------------------------------------

function updateScheduleUI() {
  const freq = document.getElementById('backup_schedule').value;
  document.querySelectorAll('.schedule-time-row').forEach(el => el.classList.toggle('d-none', freq === 'off'));
  document.querySelectorAll('.schedule-dow-row').forEach(el  => el.classList.toggle('d-none', freq !== 'weekly'));
  document.querySelectorAll('.schedule-dom-row').forEach(el  => el.classList.toggle('d-none', freq !== 'monthly'));
}

document.addEventListener('DOMContentLoaded', () => {
  document.getElementById('backup_schedule').addEventListener('change', updateScheduleUI);
  updateScheduleUI();
  loadStoredBackups();
});

async function saveSchedule() {
  const form = document.getElementById('scheduleForm');
  const data = new FormData(form);
  const btn  = form.querySelector('button[onclick]');
  btn.disabled = true;

  try {
    const res  = await fetch(BASE_PATH + '/settings/backup_schedule_save', { method: 'POST', body: data });
    const json = await res.json();
    const box  = document.getElementById('scheduleStatus');
    box.classList.remove('d-none', 'alert-success', 'alert-warning', 'alert-danger');

    if (!json.ok) {
      box.className = 'mt-3 alert alert-danger py-2';
      box.innerHTML = '<i class="bi bi-x-circle-fill"></i> ' + (json.error || 'Save failed');
      return;
    }

    if (!json.crontab_ok) {
      box.className = 'mt-3 alert alert-warning py-2';
      let msg = '<i class="bi bi-exclamation-triangle-fill"></i> Settings saved, but could not update crontab automatically.';
      if (json.cron_line) {
        msg += '<br>Add this line to the <code>www-data</code> crontab manually (<code>sudo crontab -u www-data -e</code>):'
             + '<pre class="mb-0 mt-2 p-2 bg-dark text-light rounded small"># steward-backup\n' + json.cron_line + '</pre>';
      }
      box.innerHTML = msg;
    } else {
      box.className = 'mt-3 alert alert-success py-2';
      box.innerHTML = json.cron_line
        ? '<i class="bi bi-check-circle-fill"></i> Schedule saved and crontab updated.'
        : '<i class="bi bi-check-circle-fill"></i> Automatic backups disabled.';
    }

    if (!json.dir_ok) {
      box.innerHTML += ' <span class="text-warning fw-semibold">Warning: backup directory is missing or not writable.</span>';
    }
  } catch (e) {
    const box = document.getElementById('scheduleStatus');
    box.className = 'mt-3 alert alert-danger py-2';
    box.innerHTML = '<i class="bi bi-x-circle-fill"></i> Request failed.';
  } finally {
    btn.disabled = false;
  }
}

// ---- Stored Backups -----------------------------------------------------

function fmtSize(bytes) {
  if (bytes < 1024)        return bytes + ' B';
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
  return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
}

async function loadStoredBackups() {
  const box = document.getElementById('storedBackupsList');
  try {
    const res  = await fetch(BASE_PATH + '/settings/backup_list_server');
    const json = await res.json();

    if (!json.dir_ok) {
      box.innerHTML = '<p class="text-muted text-center py-4 mb-0"><i class="bi bi-folder-x me-1"></i>Backup directory does not exist yet.</p>';
      return;
    }
    if (!json.files.length) {
      box.innerHTML = '<p class="text-muted text-center py-4 mb-0"><i class="bi bi-inbox me-1"></i>No stored backups yet. Click <strong>Back Up Now</strong> to create one.</p>';
      return;
    }

    let html = '<table class="table table-sm table-hover mb-0"><thead><tr>'
             + '<th>Date / Time</th><th>Size</th><th class="text-end">Actions</th></tr></thead><tbody>';
    for (const f of json.files) {
      const name = f.name.replace(/'/g, "\\'");
      html += `<tr>
        <td><i class="bi bi-file-earmark-code me-1 text-muted"></i>${f.display}</td>
        <td class="text-muted small">${fmtSize(f.size)}</td>
        <td class="text-end">
          <a href="${BASE_PATH}/settings/backup_download_server?file=${encodeURIComponent(f.name)}"
             class="btn btn-outline-secondary btn-sm me-1" title="Download">
            <i class="bi bi-download"></i>
          </a>
          <button class="btn btn-outline-danger btn-sm" onclick="deleteBackup('${name}')" title="Delete">
            <i class="bi bi-trash3"></i>
          </button>
        </td>
      </tr>`;
    }
    html += '</tbody></table>';
    box.innerHTML = html;
  } catch {
    box.innerHTML = '<p class="text-danger text-center py-3 mb-0">Failed to load backup list.</p>';
  }
}

async function runBackupNow() {
  const btn  = document.getElementById('runNowBtn');
  btn.disabled = true;
  btn.innerHTML = '<span class="spinner-border spinner-border-sm me-1"></span> Running…';

  const data = new FormData();
  data.append('csrf_token', getCsrfToken());

  try {
    const res  = await fetch(BASE_PATH + '/settings/backup_run_server', { method: 'POST', body: data });
    const json = await res.json();
    if (json.ok) {
      await loadStoredBackups();
    } else {
      if (json.status === 'backup_dir_missing') {
        let msg = '<i class="bi bi-exclamation-triangle-fill" style="color:#e6a817"></i> '
                + '<strong>Backup location is not configured.</strong>';
        if (json.can_configure_backup_dir && json.backup_settings_url) {
          msg += ' <a href="' + json.backup_settings_url + '">Configure backup location</a>';
        }
        showToast(msg, 'warning');
        return;
      }
      alert('Backup failed: ' + (json.error || 'Unknown error'));
    }
  } catch {
    alert('Request failed.');
  } finally {
    btn.disabled = false;
    btn.innerHTML = '<i class="bi bi-play-fill"></i> Back Up Now';
  }
}

function deleteBackup(name) {
  appConfirm(
    'Delete Backup',
    'Delete this backup file?',
    name,
    async () => {
      const data = new FormData();
      data.append('file', name);
      data.append('csrf_token', getCsrfToken());

      const res  = await fetch(BASE_PATH + '/settings/backup_delete_server', { method: 'POST', body: data });
      const json = await res.json();
      if (json.ok) {
        await loadStoredBackups();
      } else {
        alert('Delete failed: ' + (json.error || 'Unknown error'));
      }
    },
    'Delete'
  );
}

// ---- Restore / Reset ----------------------------------------------------

function confirmRestore() {
  appConfirm(
    'Restore Backup',
    'Restore this backup?',
    'This will PERMANENTLY replace all current data. This cannot be undone.',
    () => {
      bootstrap.Modal.getOrCreateInstance(document.getElementById('restoreProgressModal')).show();
      document.getElementById('restoreForm').submit();
    },
    'Yes, Restore'
  );
}

function openResetModal() {
  document.getElementById('resetConfirmInput').value = '';
  document.getElementById('resetSubmitBtn').disabled = true;
  bootstrap.Modal.getOrCreateInstance(document.getElementById('resetModal')).show();
  document.getElementById('resetModal').addEventListener('shown.bs.modal',
    () => document.getElementById('resetConfirmInput').focus(), { once: true });
}

document.addEventListener('DOMContentLoaded', () => {
  document.getElementById('resetConfirmInput').addEventListener('input', function () {
    const match = this.value === 'I understand';
    document.getElementById('resetSubmitBtn').disabled = !match;
    document.getElementById('resetConfirmHidden').value = this.value;
  });
});
</script>

<?php include __DIR__ . '/../includes/footer.php'; ?>
